name: os_detect
version: 2.1.0
description: Platform independent operating system detection and checking.
homepage: https://github.com/dart-lang/os_detect
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.8
