name: os_detect
version: 2.0.2-wip
description: Platform independent OS detection.
repository: https://github.com/dart-lang/os_detect

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.24.0
